language: node_js
node_js:
  - "7"
  - "6"
# note: travis has been acting up on old versions of node
#  - "5"
#  - "4"
#  - "0.12"
#  - "0.10"
#  - "0.9"
#  - "0.8"
before_install:
  - "npm install -g npm@4.3.0"
  - "npm install -g mocha@2.x voc"
  - "npm install blanket"
  - "npm install xlsjs"
  - "npm install coveralls mocha-lcov-reporter"
before_script:
  - "make init"
  - "cd test_files; make all; cd -"
after_success:
#  - "make coveralls-spin"
